// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.27.3
// source: risk_service.proto

package riskv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Decision int32

const (
	Decision_DECISION_UNSPECIFIED Decision = 0
	Decision_APPROVE              Decision = 1
	Decision_REVIEW_3DS           Decision = 2
	Decision_DECLINE              Decision = 3
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "APPROVE",
		2: "REVIEW_3DS",
		3: "DECLINE",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"APPROVE":              1,
		"REVIEW_3DS":           2,
		"DECLINE":              3,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_risk_service_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_risk_service_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_risk_service_proto_rawDescGZIP(), []int{0}
}

type RiskEvaluationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	MerchantId      string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	AccountId       string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AmountCents     int64                  `protobuf:"varint,4,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Currency        string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	CardBin         int32                  `protobuf:"varint,6,opt,name=card_bin,json=cardBin,proto3" json:"card_bin,omitempty"`
	CardFingerprint string                 `protobuf:"bytes,7,opt,name=card_fingerprint,json=cardFingerprint,proto3" json:"card_fingerprint,omitempty"`
	ClientIp        string                 `protobuf:"bytes,8,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	CvvMatch        bool                   `protobuf:"varint,9,opt,name=cvv_match,json=cvvMatch,proto3" json:"cvv_match,omitempty"`
	Is_3DsPassed    bool                   `protobuf:"varint,10,opt,name=is_3ds_passed,json=is3dsPassed,proto3" json:"is_3ds_passed,omitempty"`
	BillingCountry  string                 `protobuf:"bytes,11,opt,name=billing_country,json=billingCountry,proto3" json:"billing_country,omitempty"`
	UserCreatedAt   int64                  `protobuf:"varint,12,opt,name=user_created_at,json=userCreatedAt,proto3" json:"user_created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RiskEvaluationRequest) Reset() {
	*x = RiskEvaluationRequest{}
	mi := &file_risk_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskEvaluationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskEvaluationRequest) ProtoMessage() {}

func (x *RiskEvaluationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_risk_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskEvaluationRequest.ProtoReflect.Descriptor instead.
func (*RiskEvaluationRequest) Descriptor() ([]byte, []int) {
	return file_risk_service_proto_rawDescGZIP(), []int{0}
}

func (x *RiskEvaluationRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RiskEvaluationRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *RiskEvaluationRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RiskEvaluationRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *RiskEvaluationRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RiskEvaluationRequest) GetCardBin() int32 {
	if x != nil {
		return x.CardBin
	}
	return 0
}

func (x *RiskEvaluationRequest) GetCardFingerprint() string {
	if x != nil {
		return x.CardFingerprint
	}
	return ""
}

func (x *RiskEvaluationRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *RiskEvaluationRequest) GetCvvMatch() bool {
	if x != nil {
		return x.CvvMatch
	}
	return false
}

func (x *RiskEvaluationRequest) GetIs_3DsPassed() bool {
	if x != nil {
		return x.Is_3DsPassed
	}
	return false
}

func (x *RiskEvaluationRequest) GetBillingCountry() string {
	if x != nil {
		return x.BillingCountry
	}
	return ""
}

func (x *RiskEvaluationRequest) GetUserCreatedAt() int64 {
	if x != nil {
		return x.UserCreatedAt
	}
	return 0
}

type RiskEvaluationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Decision        Decision               `protobuf:"varint,2,opt,name=decision,proto3,enum=risk.v1.Decision" json:"decision,omitempty"`
	RiskScore       float32                `protobuf:"fixed32,3,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	ModelVersion    string                 `protobuf:"bytes,4,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	ReasonCodes     []string               `protobuf:"bytes,5,rep,name=reason_codes,json=reasonCodes,proto3" json:"reason_codes,omitempty"`
	ExecutionTimeUs int64                  `protobuf:"varint,6,opt,name=execution_time_us,json=executionTimeUs,proto3" json:"execution_time_us,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RiskEvaluationResponse) Reset() {
	*x = RiskEvaluationResponse{}
	mi := &file_risk_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskEvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskEvaluationResponse) ProtoMessage() {}

func (x *RiskEvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_risk_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskEvaluationResponse.ProtoReflect.Descriptor instead.
func (*RiskEvaluationResponse) Descriptor() ([]byte, []int) {
	return file_risk_service_proto_rawDescGZIP(), []int{1}
}

func (x *RiskEvaluationResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RiskEvaluationResponse) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *RiskEvaluationResponse) GetRiskScore() float32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *RiskEvaluationResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *RiskEvaluationResponse) GetReasonCodes() []string {
	if x != nil {
		return x.ReasonCodes
	}
	return nil
}

func (x *RiskEvaluationResponse) GetExecutionTimeUs() int64 {
	if x != nil {
		return x.ExecutionTimeUs
	}
	return 0
}

var File_risk_service_proto protoreflect.FileDescriptor

const file_risk_service_proto_rawDesc = "" +
	"\n" +
	"\x12risk_service.proto\x12\arisk.v1\"\xb2\x03\n" +
	"\x15RiskEvaluationRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12!\n" +
	"\famount_cents\x18\x04 \x01(\x03R\vamountCents\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x19\n" +
	"\bcard_bin\x18\x06 \x01(\x05R\acardBin\x12)\n" +
	"\x10card_fingerprint\x18\a \x01(\tR\x0fcardFingerprint\x12\x1b\n" +
	"\tclient_ip\x18\b \x01(\tR\bclientIp\x12\x1b\n" +
	"\tcvv_match\x18\t \x01(\bR\bcvvMatch\x12\"\n" +
	"\ris_3ds_passed\x18\n" +
	" \x01(\bR\vis3dsPassed\x12'\n" +
	"\x0fbilling_country\x18\v \x01(\tR\x0ebillingCountry\x12&\n" +
	"\x0fuser_created_at\x18\f \x01(\x03R\ruserCreatedAt\"\x81\x02\n" +
	"\x16RiskEvaluationResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12-\n" +
	"\bdecision\x18\x02 \x01(\x0e2\x11.risk.v1.DecisionR\bdecision\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x03 \x01(\x02R\triskScore\x12#\n" +
	"\rmodel_version\x18\x04 \x01(\tR\fmodelVersion\x12!\n" +
	"\freason_codes\x18\x05 \x03(\tR\vreasonCodes\x12*\n" +
	"\x11execution_time_us\x18\x06 \x01(\x03R\x0fexecutionTimeUs*N\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aAPPROVE\x10\x01\x12\x0e\n" +
	"\n" +
	"REVIEW_3DS\x10\x02\x12\v\n" +
	"\aDECLINE\x10\x032e\n" +
	"\vRiskService\x12V\n" +
	"\x13EvaluateTransaction\x12\x1e.risk.v1.RiskEvaluationRequest\x1a\x1f.risk.v1.RiskEvaluationResponseB>Z<github.com/maksimp027/chargeback_predict/api/proto/v1;riskv1b\x06proto3"

var (
	file_risk_service_proto_rawDescOnce sync.Once
	file_risk_service_proto_rawDescData []byte
)

func file_risk_service_proto_rawDescGZIP() []byte {
	file_risk_service_proto_rawDescOnce.Do(func() {
		file_risk_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_risk_service_proto_rawDesc), len(file_risk_service_proto_rawDesc)))
	})
	return file_risk_service_proto_rawDescData
}

var file_risk_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_risk_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_risk_service_proto_goTypes = []any{
	(Decision)(0),                  // 0: risk.v1.Decision
	(*RiskEvaluationRequest)(nil),  // 1: risk.v1.RiskEvaluationRequest
	(*RiskEvaluationResponse)(nil), // 2: risk.v1.RiskEvaluationResponse
}
var file_risk_service_proto_depIdxs = []int32{
	0, // 0: risk.v1.RiskEvaluationResponse.decision:type_name -> risk.v1.Decision
	1, // 1: risk.v1.RiskService.EvaluateTransaction:input_type -> risk.v1.RiskEvaluationRequest
	2, // 2: risk.v1.RiskService.EvaluateTransaction:output_type -> risk.v1.RiskEvaluationResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_risk_service_proto_init() }
func file_risk_service_proto_init() {
	if File_risk_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_risk_service_proto_rawDesc), len(file_risk_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_risk_service_proto_goTypes,
		DependencyIndexes: file_risk_service_proto_depIdxs,
		EnumInfos:         file_risk_service_proto_enumTypes,
		MessageInfos:      file_risk_service_proto_msgTypes,
	}.Build()
	File_risk_service_proto = out.File
	file_risk_service_proto_goTypes = nil
	file_risk_service_proto_depIdxs = nil
}
